### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by kikozz** [Young-Lord/QQ-History-Backup#3]
Traceback (most recent call last):
  File "D:\Desktop\QQ-History-Backup-master\QQ_History.py", line 513, in decode_silk
    raise FileNotFoundError
FileNotFoundError

Traceback (most recent call last):
  File "D:\Desktop\QQ-History-Backup-master\QQ_History.py", line 594, in main
    q.output(qq, mode)
  File "D:\Desktop\QQ-History-Backup-master\QQ_History.py", line 333, in output
    allmsg = self.message(qq, mode)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Desktop\QQ-History-Backup-master\QQ_History.py", line 259, in message
    msg_final = self.decrypt(msgdata, msg_type)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Desktop\QQ-History-Backup-master\QQ_History.py", line 202, in decrypt
    return self.decode_silk(msg)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Desktop\QQ-History-Backup-master\QQ_History.py", line 544, in decode_silk
    raise e
  File "D:\Desktop\QQ-History-Backup-master\QQ_History.py", line 513, in decode_silk
    raise FileNotFoundError
FileNotFoundError

Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Desktop\QQ-History-Backup-master\QQ_History.py", line 594, in main
    q.output(qq, mode)
  File "D:\Desktop\QQ-History-Backup-master\QQ_History.py", line 333, in output
    allmsg = self.message(qq, mode)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Desktop\QQ-History-Backup-master\QQ_History.py", line 259, in message
    msg_final = self.decrypt(msgdata, msg_type)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Desktop\QQ-History-Backup-master\QQ_History.py", line 202, in decrypt
    return self.decode_silk(msg)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Desktop\QQ-History-Backup-master\QQ_History.py", line 544, in decode_silk
    raise e
  File "D:\Desktop\QQ-History-Backup-master\QQ_History.py", line 513, in decode_silk
    raise FileNotFoundError
FileNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "D:\Desktop\QQ-History-Backup-master\GUI.py", line 27, in Enter
    QQ_History.main(base_path, qq_self, qq, group,
  File "D:\Desktop\QQ-History-Backup-master\QQ_History.py", line 603, in main
    raise BaseException("Error! See log.txt")
BaseException: Error! See log.txt

**Comment by Young-Lord** [comment]
音频文件没有找到，能发下你的目录结构吗

**Comment by Young-Lord** [comment]
根据文档说明，要使用语音导出，你应该确保存在 ptt 目录

**Comment by Young-Lord** [comment]
稍微更新了一下，你现在可以通过 导出的文件中语音消息显示 判断是目录格式不对还是文件不存在

**Comment by Young-Lord** [comment]
请问还在吗

**Comment by kikozz** [comment]
> 

还在 只是没在尝试 有时间我重新拉一下试试

**Comment by Young-Lord** [comment]
issue太久先close了，有问题再开
